spring.application.name=provider-demo
server.port=8081

discovery.client.service-name=provider-demo
discovery.client.instance-id=provider-demo-1
discovery.client.host=127.0.0.1
discovery.client.port=${server.port}
discovery.client.registry-url=http://127.0.0.1:8761
discovery.client.renewal-interval-ms=5000
