spring.application.name=real-cloud-eureka
server.port=8761

registry.eviction-interval-ms=5000

discovery.client.enabled=false
discovery.client.service-name=sample-client
discovery.client.instance-id=sample-client-1
discovery.client.host=127.0.0.1
discovery.client.port=${server.port}
discovery.client.registry-url=http://127.0.0.1:8761
discovery.client.renewal-interval-ms=5000
discovery.client.fetch-registry-interval-ms=8000
