spring.application.name=consumer-demo
server.port=8082

discovery.client.service-name=consumer-demo
discovery.client.instance-id=consumer-demo-1
discovery.client.host=127.0.0.1
discovery.client.port=${server.port}
discovery.client.registry-url=http://127.0.0.1:8761
discovery.client.renewal-interval-ms=5000
discovery.client.fetch-registry-interval-ms=8000
